forecasting/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    chart = FileField('Chart Image', validators=[FileAllowed(['jpg', 'png'])])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

forecasting/main/routes.py
from flask import render_template, request, Blueprint
from forecasting.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('index.html', title='Home')


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/community")
def community():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('community.html', title='Community', posts=posts)


@main.route("/premium")
def premium():
    return render_template('premium.html', title='Premium')

forecasting/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from forecasting import db
from forecasting.models import Post
from forecasting.posts.forms import PostForm
from forecasting.users.utils import save_picture

posts = Blueprint('posts', __name__)

@posts.route("/share", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.chart.data:
            chart_file = form.chart.data
            chart_filename = save_picture(chart_file)
            post = Post(
                title=form.title.data,
                content=form.content.data,
                author=current_user,
                chart=chart_filename  # Store the file name
            )
            db.session.add(post)
            db.session.commit()

            flash('Your Post has been created', 'success')
            return redirect(url_for('main.community'))
        else:
            flash('Invalid file type. Allowed file types are: png, jpg, jpeg, gif', 'danger')

    return render_template('share.html', title='Share Ideas', form=form, legend='New Idea')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update",  methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data

        # Check if a new file was provided in the form
        if form.chart.data:
            chart_file = form.chart.data
            chart_filename = save_picture(chart_file)
            post.chart = chart_filename

        db.session.commit()
        flash('Updated Successfully', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('share.html', title='Update Ideas', form=form, legend='Update Idea')

forecasting/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from forecasting import db, bcrypt
from forecasting.models import User, Post
from forecasting.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from forecasting.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
         hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
         user = User(firstname=form.firstname.data, lastname=form.lastname.data, email=form.email.data, password=hashed_password)
         db.session.add(user)
         db.session.commit()
         flash('Account Created Successfully!', 'success')
         return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login(): 
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
         user = User.query.filter_by(email=form.email.data).first()
         if user and bcrypt.check_password_hash(user.password, form.password.data):
             login_user(user, remember=form.remember.data)
             next_page = request.args.get('next')
             return redirect(next_page) if next_page else redirect(url_for('main.home'))
         else:
              flash('Login Unsuccessfull. Please check email and password', 'error')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout(): 
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.email.data = current_user.email
        image_file = url_for('static', filename='uploads/'
        + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:email>")
def user_posts(email):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(email=email).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', title='User', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Expired token', 'invalid')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
         hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
         user.password = hashed_password
         db.session.commit()
         flash('Password Reset Successfull!', 'success')
         return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

forecasting/templates/account.html
{% extends "layout.html"%}
{% block content %}
<h1 class="profile-heading">Welcome to User Account Profile</h1>
<div class="profile">
  <div class="user-account">
    <div>
      <img src="{{ image_file }}" alt="profile" class="user-img">
    </div>
    <div class=" user-info">
      <h3 class="user-name">{{ current_user.firstname }} {{ current_user.lastname }}</h3>
      <p class="user-email">{{ current_user.email }}</p>
    </div>
  </div>
  <form action="" method="POST" class="register-form log" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div>
      <h3>ACCOUNT INFORMATION</h3>
    </div>
    <div class="firstname">
      {{ form.firstname.label() }}
      {% if form.firstname.errors %}
      {{ form.firstname(class="register-input invalid") }}
      <div class="invalid-feedback">
        {% for error in form.firstname.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
      {{ form.firstname(class="register-input") }}
      {% endif %}
    </div>
    <div class="lastname">
      {{ form.lastname.label() }}
      {% if form.lastname.errors %}
      {{ form.lastname(class="register-input invalid") }}
      <div class="invalid-feedback">
        {% for error in form.lastname.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
      {{ form.lastname(class="register-input") }}
      {% endif %}
    </div>
    <div class="email">
      {{ form.email.label() }}
      {% if form.email.errors %}
      {{ form.email(class="register-input invalid") }}
      <div class="invalid-feedback">
        {% for error in form.email.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
      {{ form.email(class="register-input") }}
      {% endif %}
    </div>
    <div class="update-profile">
      {{ form.picture.label }}
      {{ form.picture(class="upload-new-pic") }}
      {% if form.picture.errors %}
      {% for error in form.picture.errors %}
      <span>{{ error }}</span>
      {% endfor %}
      {% endif %}
    </div>
    <div class="submit">
      {{ form.submit(class="submit") }}
    </div>
  </form>
</div>
{% endblock content %}

forecasting/templates/community.html
{% extends "layout.html"%}
{% block content %}
<h1 class="ideas">Shared Community Ideas</h1>
{% for post in posts.items %}
<div class="shared-post">
  <div>
    <img src="{{ url_for('static', filename='uploads/' + post.author.image_file)}}" alt="profile" class="user-post-img">
  </div>
  <div class="post-content">
    <a href="{{ url_for('posts.post', post_id=post.id) }}">
    <img
      src="{{ url_for('static', filename='uploads/' + post.chart) }}"
      alt="chart-img"
      class="post-content-img"
    />
    
      <h3 class="post-content-header">{{ post.title }}</h3>
    </a>
    <p class="post-author-date"><a href="{{ url_for('users.user_posts', email=post.author.email) }}">{{
        post.author.firstname
        }}, {{ post.author.lastname[0] }}</a> | {{
      post.date_posted.strftime('%Y-%m-%d') }}</p>
    <!-- <p class="post-comment">{{ post.content }}</p> -->
  </div>
</div>
{% endfor %}

<div class="pages">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  <a href="{{ url_for('main.community', page=page_num)}}" {% if page_num==posts.page %}class="current" {% endif %}>{{
    page_num }}</a>
  {% else %}
  ...
  {% endif %}
  {% endfor %}
</div>
{% endblock content %}

forecasting/templates/home.html
{% extends "layout.html" %}
{% block content %}
<section class="main-content">
  <article class="content-header">
    <div>
      <h1 class="main-header">Financial Market Forecasting</h1>
      <h3 class="submain-header">The future of trading guide</h3>
      <p class="main-paragraph">Welcome to our Elliott Wave Trading Guide Platform, a dedicated space designed to
        empower
        traders by providing them with strategic insights meticulously derived from the esteemed Elliott Wave Theory. As
        pioneers in the realm of trading guidance, our commitment extends beyond conventional practices, offering an
        extensive array of features that not only serve as a roadmap for navigating the complexities of the financial
        markets but also contribute to an enriched and enhanced trading experience. Explore the depth of our services as
        we go above and beyond, setting new standards in the world of trading guides.</p>
      <div class="login-signup">
        <a href="{{ url_for('users.register') }}" class="signup-button">Get Started</a>
      </div>
    </div>
    <div>
      <img src="/static/images/home-1.jpg" alt="cryptocurrency"
        style="width: 400px; height: 400px; border-radius: 8px;">
    </div>
  </article>
  <article class="share-header">
    <div class="share-ideas">
      <h3 class="share-heading">Forecasting the Financial Market Together...</h3>
      <p class="share-commentary">Embark on a journey with financial market forecasting, uniting visionaries in Elliott
        Wave analysis across diverse asset classes. Our platform empowers users with essential skills for thriving in
        the dynamic realms of crypto, stocks, forex, commodities, indices, ETFs, and beyond.</p>
    </div>
  </article>
  <article class="choose-article">
    <div class="choose">
      <h3 class="choose-us">Why Choose Us?</h3>
    </div>
    <div class="more-info">
      <div class="more-info-article pricing">
        <h5 class="why-heading">Competitive Pricing</h5>
        <ul class="why-list">
          <li>Enjoy the simplicity and transparency of our pricing model</li>
          <li>A one time annual fee</li>
          <li>No hidden costs, ensuring you maximize your investment</li>
        </ul>
      </div>
      <div class="more-info-article customer">
        <h5 class="why-heading">24/7 Support</h5>
        <ul class="why-list">
          <li>Our commitment to your success is unwavering</li>
          <li>Around the clock customer support</li>
          <li>Seamless trading experience globally.</li>
        </ul>
      </div>
      <div class="more-info-article expert">
        <h5 class="why-heading">Expert Analysis</h5>
        <ul class="why-list">
          <li>Proficiency in Elliott Wave Analysis</li>
          <li>Benefit from the insights of our seasoned analysts</li>
          <li>Make informed and strategic trading decisions.
          </li>
        </ul>
      </div>
    </div>
  </article>
  <article class="choose-article">
    <div class="choose">
      <h3 class="choose-us">Meet Our Analyst</h3>
    </div>
    <div class="more-info">
      <div class="more-info-article customer">
        <h5 class="analysts-heading">Suleiman Abdulazeem</h5>
        <img class="analyst-img" src="/static/images/suleiman_abdulazeem.jpeg" alt="Suleiman Abdulazeem"
          style="width: 240px; height: 240px;">
        <ul class="why-list">
          <li>Volatility and forex trader</li>
          <li>12 years trading experience</li>
          <li>Certified Market Technician (CMT)</li>
      </div>

      <div class="more-info-article expert">
        <h5 class="analysts-heading">Tope Ogundele</h5>
        <img class="analyst-img" src="/static/images/tope_ogundele.jpeg" alt="Tope Ogundele"
          style="width: 240px; height: 240px;">
        <ul class="why-list">
          <li>Crypto and commodity trader</li>
          <li>9 years investing experience</li>
          <li>Certified Financial Market Analyst (CFMA)</li>
      </div>
      <div class="more-info-article pricing">
        <h5 class="analysts-heading">Abdulrasheed Muhammed</h5>
        <img class="analyst-img" src="/static/images/muhammed_abdulrasheed.jpg" alt=""
          style="width: 240px; height: 240px;">
        <ul class="why-list">
          <li>Crypto and stock trader</li>
          <li>6 years investing experience</li>
          <li>Certified Elliott Wave Analyst (CEWA-M)</li>
      </div>
    </div>
  </article>
</section>
{% if not current_user.is_authenticated %}
{% endif %}
{% endblock content %}

forecasting/templates/index.html
{% extends "layout.html" %}
{% block content %}
<section class="main-content">
  <article class="content-header">
    <div>
      <h1 class="main-header">Financial Market Forecasting</h1>
      <h3 class="submain-header">The future of trading guide</h3>
      <p class="main-paragraph">Welcome to our Elliott Wave Trading Guide Platform, a dedicated space designed to
        empower
        traders by providing them with strategic insights meticulously derived from the esteemed Elliott Wave Theory. As
        pioneers in the realm of trading guidance, our commitment extends beyond conventional practices, offering an
        extensive array of features that not only serve as a roadmap for navigating the complexities of the financial
        markets but also contribute to an enriched and enhanced trading experience. Explore the depth of our services as
        we go above and beyond, setting new standards in the world of trading guides.</p>
      <div class="login-signup">
        <a href="{{ url_for('users.register') }}" class="signup-button">Get Started</a>
      </div>
    </div>
    <div class="home-img">
      <img src="/static/images/home-1.jpg" alt="cryptocurrency" class="home-img"
        style="width: 400px; height: 400px; border-radius: 8px;">
    </div>
  </article>
  <article class="share-header">
    <div class="share-ideas">
      <h3 class="share-heading">Forecasting the Financial Market Together...</h3>
      <p class="share-commentary">Embark on a journey with financial market forecasting, uniting visionaries in Elliott
        Wave analysis across diverse asset classes. Our platform empowers users with essential skills for thriving in
        the dynamic realms of crypto, stocks, forex, commodities, indices, ETFs, and beyond.</p>
    </div>
  </article>
  <article class="choose-article">
    <div class="choose">
      <h3 class="choose-us">Why Choose Us?</h3>
    </div>
    <div class="more-info">
      <div class="more-info-article pricing">
        <h5 class="why-heading">Competitive Pricing</h5>
        <ul class="why-list">
          <li>Enjoy the simplicity and transparency of our pricing model</li>
          <li>A one time annual fee</li>
          <li>No hidden costs, ensuring you maximize your investment</li>
        </ul>
      </div>
      <div class="more-info-article customer">
        <h5 class="why-heading">24/7 Support</h5>
        <ul class="why-list">
          <li>Our commitment to your success is unwavering</li>
          <li>Around the clock customer support</li>
          <li>Seamless trading experience globally.</li>
        </ul>
      </div>
      <div class="more-info-article expert">
        <h5 class="why-heading">Expert Analysis</h5>
        <ul class="why-list">
          <li>Proficiency in Elliott Wave Analysis</li>
          <li>Benefit from the insights of our seasoned analysts</li>
          <li>Make informed and strategic trading decisions.
          </li>
        </ul>
      </div>
    </div>
  </article>
  <article class="choose-article">
    <div class="choose">
      <h3 class="choose-us">Meet Our Analyst</h3>
    </div>
    <div class="more-info">
      <div class="more-info-article customer">
        <h5 class="analysts-heading">Suleiman Abdulazeem</h5>
        <img class="analyst-img" src="/static/images/suleiman_abdulazeem.jpeg" alt="Suleiman Abdulazeem"
          style="width: 240px; height: 240px;">
        <ul class="analyst-bio">
          <li>Volatility and forex trader</li>
          <li>12 years trading experience</li>
          <li>Certified Market Technician (CMT)</li>
      </div>

      <div class="more-info-article expert">
        <h5 class="analysts-heading">Tope Ogundele</h5>
        <img class="analyst-img" src="/static/images/tope_ogundele.jpeg" alt="Tope Ogundele"
          style="width: 240px; height: 240px;">
        <ul class="analyst-bio">
          <li>Crypto and commodity trader</li>
          <li>9 years investing experience</li>
          <li>Certified Financial Market Analyst (CFMA)</li>
      </div>
      <div class="more-info-article pricing">
        <h5 class="analysts-heading">Abdulrasheed Muhammed</h5>
        <img class="analyst-img" src="/static/images/muhammed_abdulrasheed.jpg" alt=""
          style="width: 240px; height: 240px;">
        <ul class="analyst-bio">
          <li>Crypto and stock trader</li>
          <li>6 years investing experience</li>
          <li>Certified Elliott Wave Analyst (CEWA-M)</li>
      </div>
    </div>
  </article>
</section>
{% if not current_user.is_authenticated %}
{% endif %}
{% endblock content %}

forecasting/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
    <title>Financial Market Forecast - {{title}}</title>
    {% else %}
    <title>Market Forecast</title>
    {% endif %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto:wght@400;500;700&family=Rubik:wght@400;500;700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='main.css') }}"
    />
  </head>

  <body>
    <header class="nav-bar">
      {% if current_user.is_authenticated %}
      <p class="greeting">
        Welcome {{ current_user.firstname }}, {{ current_user.lastname }}
      </p>
      {% else %}
      <p class="greeting">Welcome Anonymous</p>
      {% endif %}
      <nav class="nav-link">
        <ul class="nav">
          <li><a href="{{ url_for('main.home') }}" class="active">Home</a></li>
          <li><a href="{{ url_for('main.about') }}">About</a></li>
          <li><a href="{{ url_for('main.community') }}">Community</a></li>
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('posts.new_post') }}">Share</a></li>
          <!-- <li><a href="#">Premium</a></li> -->
          <li><a href="{{ url_for('users.account') }}">Account</a></li>
          <li><a href="{{ url_for('users.logout') }}">Logout </a></li>
          {% else %}
          <li>
            <a href="{{ url_for('users.login') }}">Login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main class="cotainer">
      <section class="content">
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock
        content %}
      </section>
      <aside class="aside">
        <div>
          <h5 class="aside-header">Contact Us</h5>
          <ul class="aside-list">
            <li>+(234)-80-6707-3513</li>
            <li>help@financialmarketforecasting.com</li>
          </ul>
        </div>
        <div>
          <h5 class="aside-header">Social</h5>
          <ul class="aside-list">
            <li><a href="#">facebook</a></li>
            <li><a href="#">twitter</a></li>
            <li><a href="#">instagram</a></li>
          </ul>
        </div>
      </aside>
    </main>
    <footer>
      <p class="copyright">
        Copyright&copy; Financial Market Forecasting.
        <span>Designed by Abdulrasheed Onimisi Muhammed</span>
      </p>
    </footer>
  </body>
</html>

forecasting/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div>
  <h1 class="signin">LOGIN</h1>
</div>
<form action="" method="POST" class="register-form log">
  {{ form.hidden_tag() }}
  <div class="email">
    {{ form.email.label() }}
    {% if form.email.errors %}
    {{ form.email(class="signin-input invalid") }}
    <div class="invalid-feedback">
      {% for error in form.email.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% else %}
    {{ form.email(class="signin-input") }}
    {% endif %}
  </div>
  <div class="password">
    {{ form.password.label() }}
    {% if form.password.errors %}
    {{ form.password(class="signin-input invalid") }}
    <div class="invalid-feedback">
      {% for error in form.password.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% else %}
    {{ form.password(class="signin-input") }}
    {% endif %}
  </div>
  <div class="form-check">
    {{ form.remember(class="form-check-input")}}
    {{ form.remember.label(class="form-check-label")}}
  </div>
  <div class="submit">
    {{ form.submit(class="submit") }}
  </div>
  <div>
    <a class="login-paragraph" href="{{ url_for('users.reset_request') }}">Forgot Password</a>
  </div>
</form>
{% endblock content %}

forecasting/templates/logout.html
{% extends "layout.html"%}
{% block content %}
<!-- <h1 class="register">Login</h1> -->

{% endblock content %}

forecasting/templates/post.html
{% extends "layout.html"%} {% block content %}
<h5 class="author-info">
  Shared by {{ post.author.firstname }}, {{ post.author.lastname[0] }} on {{
  post.date_posted.strftime('%Y-%m-%d') }}
</h5>
<div class="shared-post">
  <div>
    <img
      src="{{ url_for('static', filename='uploads/' + post.author.image_file)}}"
      alt="profile"
      class="user-post-img"
    />
  </div>
  <div class="post-content">
    <h3 class="post-content-header">{{ post.title }}</h3>
    <img
      src="{{ url_for('static', filename='uploads/' + post.chart) }}"
      alt="chart-img"
      class="post-content-img"
    />
    <p class="post-author-date">
      <a href="{{ url_for('users.user_posts', email=post.author.email) }}"
        >{{ post.author.firstname }}, {{ post.author.lastname[0] }}</a
      >
      | {{ post.date_posted.strftime('%Y-%m-%d') }}
    </p>
    <h3 class="post-analysis">Author's Commentary</h3>
    <p class="post-comment">{{ post.content }}</p>
    {% if post.author == current_user %}
    <div class="update-idea">
      <a
        class="sub-update"
        href="{{ url_for('posts.update_post', post_id=post.id)}}"
        >Update Idea</a
      >
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

forecasting/templates/premium.html
{% extends "layout.html"%}
{% block content %}
<h1 class="ideas">Premium Ideas</h1>
{% endblock content %}

forecasting/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div>
  <h1 class="signin">RESET PASSWORD</h1>
</div>
<form action="" method="POST" class="register-form log">
  {{ form.hidden_tag() }}
  <div class="email">
    {{ form.email.label() }}
    {% if form.email.errors %}
    {{ form.email(class="signin-input invalid") }}
    <div class="invalid-feedback">
      {% for error in form.email.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% else %}
    {{ form.email(class="signin-input") }}
    {% endif %}
  </div>
  <div class="submit">
    {{ form.submit(class="submit") }}
  </div>
</form>
{% endblock content %}

forecasting/templates/reset_token.html
{% extends "layout.html"%}
{% block content %}
<div>
  <h1 class="register">RESET PASSWORD</h1>
</div>

<form action="" method="POST" class="register-form log">
  <div class="password">
    {{ form.password.label() }}
    {% if form.password.errors %}
    {{ form.password(class="register-input invalid") }}
    <div class="invalid-feedback">
      {% for error in form.password.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% else %}
    {{ form.password(class="register-input") }}
    {% endif %}
  </div>
  <div class="confirm-password">
    {{ form.confirm_password.label() }}
    {% if form.confirm_password.errors %}
    {{ form.confirm_password(class="register-input invalid") }}
    <div class="invalid-feedback">
      {% for error in form.confirm_password.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% else %}
    {{ form.confirm_password(class="register-input") }}
    {% endif %}
  </div>
  <div class="submit">
    {{ form.submit(class="submit") }}
  </div>
</form>

{% endblock content %}

forecasting/templates/user_posts.html
{% extends "layout.html"%}
{% block content %}
<h1 class="ideas">Posts by {{ user.firstname }}, {{ user.lastname[0] }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<div class="shared-post">
  <div>
    <img src="{{ url_for('static', filename='uploads/' + post.author.image_file)}}" alt="profile" class="user-post-img">
  </div>
  <div class="post-content">
    <a href="{{ url_for('posts.post', post_id=post.id) }}">
      <h3 class="post-content-header">{{ post.title }}</h3>
    </a>
    <p class="post-author-date">{{ post.author.firstname
      }}, {{ post.author.lastname[0] }} | {{
      post.date_posted.strftime('%Y-%m-%d') }}</p>
    <p class="post-comment">{{ post.content }}</p>
  </div>
</div>
{% endfor %}

<div class="pages">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  <a href="{{ url_for('users.user_posts', email= user.email, page=page_num)}}" {% if page_num==posts.page
    %}class="current" {% endif %}>{{
    page_num }}</a>
  {% else %}
  ...
  {% endif %}
  {% endfor %}
</div>
{% endblock content %}